[package]
name = "shiguredo_openh264"
version = "2026.1.0-canary.1"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
description = "Rust binding for OpenH264"
repository = "https://github.com/shiguredo/openh264-rs"
build = "build.rs"

[build-dependencies]
bindgen = "0.72"
shiguredo_toml = "2026.1.0"

# 以降は外部ライブラリビルド用のメタデータ
# (この内容は build.rs の中からのみ参照される)
[package.metadata.external-dependencies]
openh264 = { git = "https://github.com/cisco/openh264.git", version = "v2.6.0" }

[dev-dependencies]
raden = "2026.1.0-canary"
mp4 = "0.14"

[workspace]
members = []
exclude = []
